required = ["github.com/golang/protobuf/protoc-gen-go"]

[[override]]
  name = "k8s.io/client-go"
  branch = "release-6.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.6"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.6"

[prune]
  go-tests = true
  unused-packages = true
